# Generated by Django 3.0.1 on 2020-01-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_dazhongdianping_liren_all_data_dazhongdianping_liren_new_all_data_dazhongdianping_liren_signing_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dazhongdianping_liren_all_data',
        ),
        migrations.DeleteModel(
            name='Dazhongdianping_liren_new_all_data',
        ),
        migrations.DeleteModel(
            name='Dazhongdianping_liren_signing_data',
        ),
        migrations.DeleteModel(
            name='Dazhongdianping_liren_user_data',
        ),
        migrations.DeleteModel(
            name='Setting_storage',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Work_order',
        ),
    ]
